#!/bin/bash
# migrator.conf - конфигурация мигратора

# Параметры подключения к БД
export DB_NAME="rpp"
export DB_USER="postgres"
export DB_HOST="localhost"
export DB_PORT="5432"


# Путь к директории с миграциями
export MIGRATIONS_DIR="./sql_migrations"
