name: Deploy Lab-4 to GitHub Pages on Release

on:
  release:
    types: [published]  # Запуск только при публикации релиза

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: lab-4  # Директория с сайтом 
          publish_branch: gh-pages  # Ветка для публикации
          destination_dir: v${{ github.event.release.tag_name }}  # Поддиректория v{тег}, например v1.0
          force_orphan: false  # Не стирать историю
          keep_files: true  # Сохранять существующие файлы для прошлых версий