name: Deploy Lab-4 to GitHub Pages on Release

on:
  release:
    types: [published]  # Запуск при публикации релиза

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: lab-4  # Берем файлы из lab-4
          publish_branch: master
          destination_dir: lab-4/v${{ github.event.release.tag_name }}  # Поддиректория lab-4/v{тег}
          force_orphan: false
          keep_files: true  # Сохраняем прошлые версии